encoder_id: ViT-bigG/14
dataset: coco
hist_kind: rgb512
epochs: 300
batch_size: 4096
val_batch_size: 8192
optimizer: AdamW
betas:
- 0.9
- 0.999
weight_decay: 0.001
scheduler: null
scheduler_params: {}
top_k: 20
regularizers:
  blur: 0.01
  lambda_ortho: 0.2
  lambda_consistency: 0.1
  lambda_leak: 0.25
precision: fp16
seed: 42
device: cuda
