encoder_id: ViT-H/14
dataset: unknown
hist_kind: hcl514
epochs: 2
batch_size: 4096
val_batch_size: 8192
optimizer: AdamW
betas:
- 0.9
- 0.999
weight_decay: 0.01
scheduler: null
scheduler_params: {}
top_k: 100
regularizers:
  blur: 0.05
  lambda_ortho: 0.1
  lambda_consistency: 0.1
  lambda_leak: 0.25
precision: fp16
seed: 42
device: cuda
